# Generated by Django 5.2.1 on 2025-05-27 03:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='membership_date',
            field=models.DateTimeField(null=True),
        ),
    ]
