# Generated by Django 5.2.1 on 2025-06-29 08:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0004_alter_article_created_at_alter_ratings_value'),
    ]

    operations = [
        migrations.CreateModel(
            name='MustReadArticle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('headline', models.CharField(max_length=300)),
                ('body', models.TextField()),
                ('publishing_date', models.DateTimeField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mustReadArticle', to='article.author')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mustReadArticle', to='article.category')),
            ],
        ),
    ]
