# Generated by Django 5.2.1 on 2025-10-30 22:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0007_dontmissarticleimage_mustreadarticleimage_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='types',
            field=models.CharField(choices=[('normal', 'Normal'), ('popular', 'Popular'), ('mustread', 'Must Read'), ('dontmiss', 'Don’t Miss')], default='normal', max_length=20),
        ),
    ]
